version: "3.8"

services:
  redis_cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./server
    restart: always
    depends_on:
      redis_cache:
        condition: service_healthy
    environment:
      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
    expose:
      - "4050"

  frontend:
    build: ./client
    restart: always
    depends_on:
      - backend
    expose:
      - "3000"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
